#! /usr/bin/env python
# _*_ coding: utf-8 _*_
# @FileName :抢课.py
# @Time : 2022/3/4 13:07
# @Author : NGUBIN
import re
import base64
import time

import requests
from random import choice
from textwrap import dedent
from urllib.parse import urlencode

user_agent = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0",
]

headers = {
    'Host': 'jw.educationgroup.cn',
    'Upgrade-Insecure-Requests': '1',
    'Content-Type': 'application/x-www-form-urlencoded',
    'User-Agent': choice(user_agent),
    'Cookie': 'JSESSIONID=2C8523F623E3D36A631A7DC10A045D10; HWWAFSESID=f6cf0795dd57743eff; HWWAFSESTIME=1686629183146',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
    'Referer': 'https://jw.educationgroup.cn/gzasc_jsxsd/',
    'Accept-Language': 'zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2',
    'Connection': 'keep-alive'
}

data = {
    "sEcho": "1",
    "iColumns": "13",
    "sColumns": "",
    "iDisplayStart": "0",
    "iDisplayLength": "15",
    "mDataProp_0": "kch",
    "mDataProp_1": "kcmc",
    "mDataProp_2": "xf",
    "mDataProp_3": "skls",
    "mDataProp_4": "sksj",
    "mDataProp_5": "skdd",
    "mDataProp_6": "xqmc",
    "mDataProp_7": "xxrs",
    "mDataProp_8": "xkrs",
    "mDataProp_9": "syrs",
    "mDataProp_10": "ctsm",
    "mDataProp_11": "szkcflmc",
    "mDataProp_12": "czOper",
}


# 说明
def readme():
    print(dedent('''\
        **********  Created By NGUBIN  ***************
                        Version : 0.0.1
           基于GPL3.0，完全开源，免费，禁止二改或商用
            https://github.com/Homby/Rush-lesson
                        仅供学习，勿滥用
        **********************************************
    '''))


# 登录
def login():
    username = input("请输入你的学号:")
    password = input("请输入你的密码:")
    a = s.get("https://jw.educationgroup.cn/gzasc_jsxsd/verifycode.servlet")
    with open("code.jpg", "wb") as f:
        f.write(a.content)
    print('Login...')
    # 构造登录密码
    values = {'userAccoun': username, 'userPassword': ''}
    login_code = base64.b64encode(bytes(username, 'utf8')).decode() + '%%%' + base64.b64encode(
        bytes(password, 'utf8')).decode()
    values['encoded'] = login_code
    login_data = urlencode(values).encode('utf-8')
    print(login_data)
    # 登录
    a = s.post("https://jw.educationgroup.cn/gzasc_jsxsd/xk/LoginToXk", data=login_data, headers=headers)
    a = s.get('https://jw.educationgroup.cn/gzasc_jsxsd/framework/xsMain.jsp', headers=headers)
    print(a)

    if a.status_code == 200:
        try:
            user_name = re.search(r'white">(?P<my_name>.*?)</a>', a.text).group('my_name')  # 获取真实姓名
            print("\n ", "用户:", user_name, "\t登录成功\n")
        except:
            print("\n获取用户失败!\n")

        print("正在跳转.......")
        time.sleep(1)
        target()
    else:
        print("\n登录失败 学号或密码错误，请重试！\n")
        exit(0)


# 检索选课中心出现的限时选课列表并且获取url, 目前没有对只存在1个与多个选课列表进行判断,出现多个列表时将出现bug
def target():
    a = s.get('https://jw.educationgroup.cn/gzasc_jsxsd/xsxk/xklc_list', headers=headers)
    if '未查询到数据' in a.text:
        print("未查询到数据,请确认官网是否开放选课!")
        # exit(0)
    else:
        try:
            select_course = re.compile(r'操作</th>.*?<td>.*?</td>.*?<td>(?P<cla>.*?)</td>.*?"jrxk" href=".*?id=(?P<cla_id>.*?)">.*?sUrl="(?P<cla_url>.*?)"', re.S)
            my_course = select_course.search(a.text)  # 截取选课名称(cla)以及选课链接(cla_url+cla_id), 通过下方拼接成入口
            enter_url = "https://jw.educationgroup.cn" + my_course.group('cla_url') + my_course.group('cla_id')
            print("获取到选课列表:\n", my_course.group('cla'), "\t链接:", enter_url)
            a = s.get(enter_url, headers=headers)
            center_url = "https://jw.educationgroup.cn/gzasc_jsxsd/xsxkkc/comeInGgxxkxk"
            a = s.post(center_url, headers=headers)
            choose()
        except:
            print("数据异常!")
            exit(0)


# 选课页, 筛选课程并进行抢课
def choose():
    """
    上一轮选课类别代号(szjylb):
    " "---所有课程
    "1"---人文科学
    "2"---自然科学
    "3"---社会科学
    "4"---工程技术
    "5"---人文社会科学类
    "6"---自然科学技术类
    "7"---美育（艺术）类
    "8"---创新教育类
    "9"---其它
    """
    """
    kcxx
    skls上课老师
    skxq选课星期
    skjc选课节次
    sfym过滤已满课程
    sfct过滤冲突课程
    szjylb选课类别
    sfxx过滤限选
    """

    lesson_list = "https://jw.educationgroup.cn/gzasc_jsxsd/xsxkkc/xsxkGgxxkxk?kcxx=&skls=&skxq=&skjc=&sfym=false&sfct=false&szjylb=&sfxx=false"
    a = s.post(lesson_list, data, headers=headers)
    print(a.text)
    try:

        for aa in a.json()['aaData']:
            print("选课类别: "+aa['szkcflmc']+"   \t\t上课时间: "+aa['xnxq01id']+""+aa['sksj']+"\t\t课程名称: "+aa['kcmc']+"\t\t选课地点: "+aa['skdd'] +"   \t\t选课类型: "+aa['kcxzmc']+"\t\tkcid: "+aa['jx02id']+"  \t\tjx0404id: "+aa['jx0404id'])
            if "岩" in aa['kcmc']:
                print("正在选取课程:", aa['kcmc'])
                go_url = "https://jw.educationgroup.cn/gzasc_jsxsd/xsxkkc/ggxxkxkOper?kcid=" + aa['jx02id'] + "&cfbs=null&jx0404id=" + aa['jx0404id'] + "&xkzy=&trjf=&_=1677565944000"
                a = s.post(go_url, data, headers=headers)
                print(a.json())
                # break


        # for it in claa:
        #     print("正在选取课程:", it.group('clname'))
        #     go_url = "https://jw.educationgroup.cn/gzasc_jsxsd/xsxkkc/ggxxkxkOper?kcid=" + it.group('kcid') + "&cfbs=null&jx0404id=" + it.group('cid') + "&xkzy=&trjf=&_=1677565944000"
        #     a = s.post(go_url, data, headers=headers)
    except:
        print("查询失败!")





if __name__ == "__main__":
    s = requests.session()
    readme()
    login()
